name: Git-Hub-Profile-AtCoder

on:
  schedule: # JST 月曜日 03:00 == UTC 日曜日 18:00
    - cron: "0 18 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-Git-Hub-Profile-AtCoder
    steps:
      - uses: actions/checkout@v3
      - uses: kinakomoch7/git-hub-profile-atcoder@v0.2.0
        env:
          USER_NAME: inoue_r
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
